language: python

python:
  - 2.7

install:
  - curl -sSfLo vault2env https://github.com/Luzifer/vault2env/releases/download/v0.6.1/vault2env_linux_amd64
  - chmod +x vault2env
  - export PATH=$PATH:$(pwd)

script:
  - vault2env secret/private/screeps -- make publish_${TRAVIS_BRANCH}
